import mongoose from 'mongoose'

const moveSchema = new mongoose.Schema({
  cBusinessName: String,
  cCountry: String,
  cDate: Date,
  cEmail: String,
  cName: String,
  cPhone: String,
  cPostCode: String,
  cStreet: String,
  cTime: String,
  cTwon: String,
  co2Emissions: Number,
  colour: String,
  dBusinessName: String,
  dCountry: String,
  dDate: Date,
  dEmail: String,
  dName: String,
  dPhone: String,
  dPostCode: String,
  dStreet: String,
  dTime: String,
  dTwon: String,
  dateOfLastV5CIssued: Date,
  engineCapacity: Number,
  euroStatus: String,
  fuelType: String,
  hosValidMot: Boolean,
  make: String,
  markedForExport: Boolean,
  monthOfFirstRegistration: String,
  motExpiryDate: Date,
  motStatus: String,
  realDrivingEmissions: String,
  registrationNumber: String,
  revenueWeight: Number,
  taxDueDate: Date,
  taxStatus: String,
  transportMethod: String,
  typeApproval: String,
  wheelplan: String,
  yearOfManufacture: Number,
  poc: String,
  pod: String,
  deliveryNote: String,
  cancelNote: String,
  status: {
    type: String,
    default: 'active',
  },
  userId: String,
})

const Moves = mongoose.model('Moves', moveSchema)

export default Moves
